"""Coluna current_hps na ongoing_battles

Revision ID: 2005cf718560
Revises: 66ee0b272a8f
Create Date: 2024-08-21 15:19:47.368241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2005cf718560'
down_revision: Union[str, None] = '66ee0b272a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ongoing_battles', sa.Column('current_hps', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ongoing_battles', 'current_hps')
    # ### end Alembic commands ###
