"""Revisão nome colunas

Revision ID: 572da06751e8
Revises: b8509d7678b0
Create Date: 2024-08-02 17:11:22.864700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572da06751e8'
down_revision: Union[str, None] = 'b8509d7678b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('participant_monsters', sa.String(), nullable=True))
    op.add_column('battles', sa.Column('participant_characters', sa.String(), nullable=True))
    op.drop_column('battles', 'paricipant_characters')
    op.drop_column('battles', 'paricipant_monsters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('paricipant_monsters', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('battles', sa.Column('paricipant_characters', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('battles', 'participant_characters')
    op.drop_column('battles', 'participant_monsters')
    # ### end Alembic commands ###
