"""Adicionado coluna na OngoingBattle

Revision ID: 66ee0b272a8f
Revises: 572da06751e8
Create Date: 2024-08-15 13:49:20.931212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ee0b272a8f'
down_revision: Union[str, None] = '572da06751e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ongoing_battles', sa.Column('participants_initiative_order', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ongoing_battles', 'participants_initiative_order')
    # ### end Alembic commands ###
