"""Added dead_participants to OngoingBattle table

Revision ID: 97770327aa7d
Revises: 2005cf718560
Create Date: 2024-08-26 16:00:53.944549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97770327aa7d'
down_revision: Union[str, None] = '2005cf718560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ongoing_battles', sa.Column('dead_participants', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ongoing_battles', 'dead_participants')
    # ### end Alembic commands ###
