"""Migration voltou separação dos participantes

Revision ID: b8509d7678b0
Revises: f525df17ce3b
Create Date: 2024-08-02 17:00:59.233274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8509d7678b0'
down_revision: Union[str, None] = 'f525df17ce3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('paricipant_monsters', sa.String(), nullable=True))
    op.add_column('battles', sa.Column('paricipant_characters', sa.String(), nullable=True))
    op.add_column('ongoing_battles', sa.Column('participant_characters', sa.String(), nullable=True))
    op.add_column('ongoing_battles', sa.Column('participant_monsters', sa.String(), nullable=True))
    op.add_column('ongoing_battles', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('ongoing_battles', 'participant_list')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ongoing_battles', sa.Column('participant_list', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ongoing_battles', 'status')
    op.drop_column('ongoing_battles', 'participant_monsters')
    op.drop_column('ongoing_battles', 'participant_characters')
    op.drop_column('battles', 'paricipant_characters')
    op.drop_column('battles', 'paricipant_monsters')
    # ### end Alembic commands ###
